POST {{url}}/notifications
Content-Type: application/json

{
  "to_id": 1234,
  "message": "какое-то оповещение",
  "repeat_interval": "minute",
  "since_timestamp": "2025-03-09T13:03:00+03:00"
}
###

//  "last_sent_timestamp": "",
