openapi: 3.0.3
info:
  title: NotifSystemService
  description: Service that fetches notif's dbs and pushes notifs to notif service
  version: 0.1.0
servers:
  - url: 'https'
tags:
  - name: notifications
  - name: user_preferences
paths:
  /notifications:
    post:
      tags:
        - notifications
      summary: create new notification
      description: since_timestamp should be greater than now
      operationId: addNotification
      requestBody:
        description: Create a new notification
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewNotification'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessInsertResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      tags:
        - notifications
      summary: get notification
      description: get notification by id
      operationId: getNotifications
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '404':
          description: Not found at db
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /notifications/{notif_id}:
    delete:
      tags:
        - notifications
      summary: delete a notification
      operationId: delNotification
      parameters:
        - name: notif_id
          in: path
          schema:
            type: integer
          required: true
          description: Numeric ID of the notification to delete
      responses:
        '204':
          description: Successful operation
        '404':
          description: not found at db
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      tags:
        - notifications
      summary: get notification
      description: get notification by id
      operationId: getNotification
      parameters:
        - name: notif_id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '404':
          description: Not found at db
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /userprefs:
    get:
      tags:
        - user_preferences
      summary: get users preferences
      operationId: getUserPrefs
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserPreferences'
        '404':
          description: Not found at db
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags:
        - user_preferences
      summary: create new user preferences
      operationId: createUserPref
      requestBody:
        description: Create a new user preferences
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPreferences'
            example: 
              user_id: 3124
              dont_disturb_start: '23:00+03'
              dont_disturb_end: '07:30+03'
              
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessInsertResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /userprefs/{user_pref_id}:
    delete:
      tags:
        - user_preferences
      summary:  delete user_preferences
      operationId: delUserPrefs
      parameters:
        - name: user_pref_id
          in: path
          schema:
            type: integer
          required: true
          description: Numeric ID of the user_pref to delete
      responses:
        '204':
          description: Successful operation
        '404':
          description: not found at db
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
          tags:
            - user_preferences
          summary: get user preferences
          operationId: getUserPrefsById
          parameters:
            - name: user_pref_id
              in: path
              schema:
                type: integer
              required: true
          responses:
            '200':
              description: Successful operation
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/UserPreferences'
            '404':
              description: Not found at db
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorResponse'
            '500':
              description: Internal error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    NewNotification:
      type: object
      properties:
        to_id:
          type: integer
        message:
          type: string
        repeat_interval:
          type: string
          enum:
            - no-repeat
            - minute
            - half-hour
            - hour
            - day
            - week
            - month
        since_timestamp:
          type: string
          example: 2026-03-09T13:03:00+03:00
      required:
        - to_id
        - message
        - repeat_interval
        - since_timestamp
    
    Notification:
      type: object
      properties:
        id:
          type: integer
        to_id:
          type: integer
        repeat_interval:
          type: string
          enum:
            - minute
            - no-repeat
            - half-hour
            - hour
            - day
            - week
            - month
        message:
          type: string
          example: "this is an any notification"
        created_at:
          type: string
          example: "2025-03-11T19:27:49.367887Z"
        last_sent_timestamp:
          type: string
          example: "2026-03-09T10:03:00Z"
        since_timestamp:
          type: string
          example: "2026-03-09T10:03:00Z"
    
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
    
    SuccessInsertResponse:
      type: object
      properties:
        id:
          type: integer
    
    UserPreferences:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        dont_disturb_start:
          type: string
          example: "23:00+03"
        dont_disturb_end:
          type: string
          example: "07:30+03"
        created_at:
          type: string
          example: "2026-03-08T10:03:00Z"
        updated_at:
          type: string
          example: "2026-03-09T10:03:00Z"
      example:
        {
          "id": 87268,
          "user_id": 3124,
          "dont_disturb_start": "23:00+03",
          "dont_disturb_end": "07:30+03",
          "created_at": "2026-03-08T10:03:00Z",
          "updated_at": "2026-03-09T10:03:00Z",
        }

